apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: example
  namespace: default
spec:
  rules:
    - host: cluster.dogukanturan.com
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 8080
            path: /
