apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-password-generator
spec:
  selector:
    matchLabels:
      app: flask-password-generator
  template:
    metadata:
      labels:
        app: flask-password-generator
    spec:
      containers:
      - name: flask-password-generator
        image: dturan/flask-password-generator:latest
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-password-generator
spec:
  selector:
    app: flask-password-generator
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: flask-password-generator
  namespace: default
spec:
  rules:
    - host: cluster.local
      http:
        paths:
          - backend:
              serviceName: flask-password-generator
              servicePort: 8080
            path: /
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-password-generator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-password-generator
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50