name: Flask Password Generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
      - name: Docker Build
        run: |
          docker build -t dturan/flask-password-generator:latest . 
      - name: Docker Push
        run: |
          docker push dturan/flask-password-generator:latest
